PLAT-135698: Migrate samples from internal-samples repo
enactjs/moonstone pull request #45
Opened 2021-03-05 11:35 UTC by adrian-cocoara-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed

* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Migrate samples from internal-samples repo

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Migrated samples from internal-samples repo

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
There are some local lint warnings: 'React' is defined but never user. This warning appears in every sample. 
Travis fails because some failed unit tests, maybe a code restructure of each unit test to support react 17 would be needed in another ticket.

### Links
PLAT-135698

### Comments

Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com

2021-03-05 13:35 UTC, daniel-stoian-lgp approved these changes

2021-03-19 05:56 UTC, seunghoh requested changes
Moonstone doesn't have `scrollMode` prop. 
Please check the console warning
```
index.js:1 Warning: React does not recognize the `scrollMode` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrollmode` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

2021-03-23 01:25 UTC, seunghoh requested changes
I see more warnings in the qa-a11y > EditableIntegerPicker
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

```

2021-03-26 05:44 UTC, seunghoh approved these changes

2021-03-26 05:44 UTC, merged